<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LightInject.Microsoft.Hosting" Version="2.2.0" />
    <PackageReference Include="CQRS.LightInject" Version="2.1.0" />
  </ItemGroup>
</Project>